[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.local/share/rofi/themes/material-you/colors.rasi'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors.vim'
output_path = '~/.config/nvim/colors/matugen.vim'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty.conf'
output_path = '~/.config/ghostty/auto/theme.ghostty'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf || true'

