local programs = require("modules.programs")

hl.on("hyprland.start", function()
  hl.exec_cmd("qs")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("dunst")
  hl.exec_cmd("discord-canary")
  hl.exec_cmd("zen-twilight")
  hl.exec_cmd("ghostty")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)
