set -gq @thm_bg                           "{{colors.background.default.hex}}"
set -gq @thm_fg                           "{{colors.on_background.default.hex}}"
set -gq @thm_primary                      "{{colors.primary.default.hex}}"
set -gq @thm_inverse_primary              "{{colors.inverse_primary.default.hex}}"
set -gq @thm_surface_low                  "{{colors.surface_container_lowest.default.hex}}"
set -gq @thm_surface                      "{{colors.surface.default.hex}}"
set -gq @thm_surface_variant              "{{colors.surface_container.default.hex}}"
set -gq @thm_outline                      "{{colors.outline.default.hex}}"
set -gq @thm_text_variant                 "{{colors.on_surface_variant.default.hex}}"

set -g @minimal-tmux-fg "#{@thm_primary}"
set -g @minimal-tmux-bg "#{@thm_surface_variant}"
