set -gq @thm_bg                           "#141318"
set -gq @thm_fg                           "#e6e1e9"
set -gq @thm_primary                      "#cebdfe"
set -gq @thm_inverse_primary              "#64558f"
set -gq @thm_surface_low                  "#1c1b20"
set -gq @thm_surface                      "#211f24"
set -gq @thm_surface_variant              "#2b292f"
set -gq @thm_outline                      "#48454e"
set -gq @thm_text_variant                 "#cac4cf"


set -g @minimal-tmux-fg "#{@thm_primary}"
set -g @minimal-tmux-bg "#{@thm_surface_variant}"
